[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "adventofcode2023day01"
path = "day01/main.rs"

[[bin]]
name = "adventofcode2023day02"
path = "day02/main.rs"
